package docgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/richarddavenport/tuikit/harness"
)

// Markdown writes the capture as a Markdown document with an image per frame.
//
// The page HTML produces is one file you open. This is the other thing people
// need: something that goes IN a repository — a README, an mkdocs site, a pull
// request — where a self-contained HTML page cannot go and a fenced block of
// ANSI escape codes renders as noise.
//
// out names the Markdown file. The images are written beside it, in a directory
// named after it: `docs/screens.md` gets `docs/screens/`. Beside rather than
// in a shared assets directory, because a document and its images are moved,
// renamed and deleted together, and a convention that makes that one operation
// is a convention nobody has to remember.
//
// The images are SVG. See SVG for why not PNG — the short version is that a
// PNG needs a typeface and tuikit has deliberately not chosen one.
//
// Every file is written from the capture, so the document has no state of its
// own: run it again and what changed in the tool is what changes in the diff.
// That is the property that makes it worth committing.
func (f Frames) Markdown(dir, out string) error {
	manifest, err := readManifest(dir)
	if err != nil {
		return err
	}

	byName := make(map[string]harness.Frame, len(manifest.Frames))
	for _, fr := range manifest.Frames {
		byName[fr.Name] = fr
	}

	assets := strings.TrimSuffix(out, filepath.Ext(out))
	if err := os.MkdirAll(assets, 0o755); err != nil {
		return fmt.Errorf("docgen: %w", err)
	}
	rel := filepath.Base(assets)

	title := f.Title
	if title == "" {
		title = filepath.Base(dir)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	if f.Lede != "" {
		fmt.Fprintf(&b, "%s\n\n", f.Lede)
	}
	fmt.Fprintf(&b, "%d frames at %d×%d. Generated by `tuikit frames`; edit the capture, not this file.\n",
		len(manifest.Frames), manifest.Width, manifest.Height)

	for _, sec := range f.sections(manifest, byName) {
		fmt.Fprintf(&b, "\n## %s\n", sec.Title)
		if sec.Lede != "" {
			fmt.Fprintf(&b, "\n%s\n", sec.Lede)
		}
		for _, note := range sec.Notes {
			fr := byName[note.Name]
			raw, err := os.ReadFile(filepath.Join(dir, fr.File))
			if err != nil {
				return fmt.Errorf("docgen: %w", err)
			}
			img := note.Name + ".svg"
			if err := os.WriteFile(filepath.Join(assets, img), []byte(SVG(string(raw))), 0o600); err != nil {
				return fmt.Errorf("docgen: %w", err)
			}

			fmt.Fprintf(&b, "\n### %s\n", note.Name)
			if note.Note != "" {
				fmt.Fprintf(&b, "\n%s\n", note.Note)
			}
			if note.Keys != "" {
				fmt.Fprintf(&b, "\nKeys: %s\n", keycaps(note.Keys))
			}
			// The alt text is the note when there is one, because "a screenshot
			// of the tool" tells a reader who cannot see it nothing they could
			// not guess. The frame name is the fallback, not the first choice.
			alt := note.Note
			if alt == "" {
				alt = note.Name
			}
			fmt.Fprintf(&b, "\n![%s](%s/%s)\n", escapeAlt(alt), rel, img)
			if string(fr.Mode) != "" && string(fr.Mode) != "live" {
				fmt.Fprintf(&b, "\n*%s · %d×%d*\n", fr.Mode, fr.Width, fr.Lines)
			}
		}
	}

	return os.WriteFile(out, []byte(b.String()), 0o600)
}

// keycaps renders a key sequence as inline code, one span per key: `tab` `→`.
func keycaps(keys string) string {
	fields := strings.Fields(keys)
	out := make([]string, 0, len(fields))
	for _, k := range fields {
		out = append(out, "`"+k+"`")
	}
	return strings.Join(out, " ")
}

// escapeAlt keeps a note with a bracket in it from ending the alt text early.
func escapeAlt(s string) string {
	r := strings.NewReplacer("[", "\\[", "]", "\\]", "\n", " ")
	return r.Replace(s)
}
